### ISSUE TITLE
sbin/mount.vboxsf: mounting failed with the error: No such device

### ISSUE THREAD

**Issue by vbmade2000** [CentOS/sig-cloud-instance-build#102]
I have got below error when using centos/7 box from https://app.vagrantup.com/centos/boxes/7.

```Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

Vagrant Version: 1.9.7

**Comment by lpancescu** [comment]
This is a duplicate of issue #27 (the VirtualBox guest additions aren't preinstalled - if you change the sync method from rsync to virtualbox, you're going to get this error). Please don't file issues here for things already covered in the [release notes][1].

[1]: https://seven.centos.org/2017/08/updated-centos-vagrant-images-available-v1707-01/

**Comment by vbmade2000** [comment]
Ok. Thanks.
