### ISSUE TITLE
[BUG REPORT]  KeyboardInterrupt error of "yum update"

### ISSUE THREAD

**Issue by cxxly** [CentOS/sig-cloud-instance-build#26]
[BUG REPORT]  

# cat /etc/redhat-release 
CentOS Linux release 7.0.1406 (Core)   

# uname -a
Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

#yum update
...
Total download size: 594 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for base
updates/7/x86_64/prestodelta                               | 240 kB   00:41     
Delta RPMs reduced 35 M of updates to 3.1 M (91% saved)
(1/566): flac-libs-1.3.0-4.el7_1.3.0-5.el7_1.x86_64.drpm   |  27 kB   00:02     
(2/566): freetype-2.4.11-9.el7_2.4.11-10.el7_1.1.x86_64.dr |  62 kB   00:05     
(3/566): gdk-pixbuf2-2.28.2-4.el7_2.28.2-5.el7_1.x86_64.dr |  75 kB   00:01     
(4/566): iputils-20121221-6.el7_20121221-6.el7_1.1.x86_64. | 110 kB   00:00     
(5/566): libuser-0.60-5.el7_0.60-7.el7_1.x86_64.drpm       | 122 kB   00:00     
(6/566): libuser-python-0.60-5.el7_0.60-7.el7_1.x86_64.drp |  35 kB   00:00     
(7/566): python-2.7.5-16.el7_2.7.5-18.el7_1.1.x86_64.drpm  |  58 kB   00:00     
(8/566): python-chardet-2.0.1-7.el7_2.2.1-1.el7_1.noarch.d |  42 kB   00:00     
Traceback (most recent call last):              ] 108 kB/s | 715 kB   88:26 ETA 
  File "/usr/libexec/urlgrabber-ext-down", line 75, in <module>
    main()
  File "/usr/libexec/urlgrabber-ext-down", line 61, in main
    fo = PyCurlFileObject(opts.url, opts.filename, opts)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1258, in __init__
    self._do_open()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1589, in _do_open
    self._do_grab()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1723, in _do_grab
    self._do_perform()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1517, in _do_perform
    raise KeyboardInterrupt
KeyboardInterrupt
(13/566): python-libs-2.7. 0% [                 ] 120 kB/s | 807 kB   80:02 ETA 

Exiting on user cancel

**Comment by jperrin** [comment]
There isn't any detail in this report. Was this inside a container or on the host?

**Comment by cxxly** [comment]
On the vmware virtual machine, I've found a related bug report for Red Hat(https://bugzilla.redhat.com/show_bug.cgi?id=1091740), but it hasn't resulted in anything and the suggestions in it do not work for me. Maybe we should close this issue and open it in centos community.

**Comment by kbsingh** [comment]
we dont publish a vmware virtual machine, so can you point out exactly what url you get the image from and how / what you processed it as ? I'm assuming you got one of the qcow2 images and did a disk import perhaps ?
