### ISSUE TITLE
We should have rsync and screen RPM in the vagrant box

### ISSUE THREAD

**Issue by LalatenduMohanty** [CentOS/sig-cloud-instance-build#29]
Having the rsync package in the Vagrant box helps to start the vagrant box quickly on a Linux host. As for each "vagrant up" on Linux/GNU (with libvirt) Vagrant installs rsync from internet. 
Having screen helps a developer environment.

**Comment by kbsingh** [comment]
+1 to rsync, I'm mostly +/- 0 for screen ( dont most people use tmux these days ? )

**Comment by kbsingh** [comment]
added https://github.com/CentOS/sig-cloud-instance-build/commit/19a7e0bbd6b945636ce0c33f723ff09fb46b0183

**Comment by LalatenduMohanty** [comment]
@kbsingh screen is required for https://github.com/purpleidea/oh-my-vagrant project work with the CentOS base images. Also teh world is divided between screen vs tmux :). We have users for both. I think if it is just matter of less than <1MB , We should add screen.

**Comment by LalatenduMohanty** [comment]
Just confirmed screen package will bring in extra 550KB.
