### ISSUE TITLE
Vagrant box's root user should have password 'vagrant'

### ISSUE THREAD

**Issue by LalatenduMohanty** [CentOS/sig-cloud-instance-build#30]
As per upstream Vagrant documentation [1] vagrant user and root user should have password 'vagrant'

[1] vagrant user and root user should have password 'vagrant'

**Comment by kbsingh** [comment]
Is not having this causing any issues ?

**Comment by mvermaes** [comment]
It shouldn't, it's just a convention. From https://docs.vagrantup.com/v2/boxes/base.html:

*"Vagrant doesn't actually use or expect any root password. However, having a generally well known root password makes it easier for the general public to modify the machine if needed.*

*Publicly available base boxes usually use a root password of "vagrant" to keep things easy."*

**Comment by LalatenduMohanty** [comment]
@mvermaes agree. @kbsingh I think it is better to match upstream Vagrant standards.

**Comment by kbsingh** [comment]
I feel that unless we know there is something being blocked or broken, it might be best to prefer security. Also note that the default vagrant user has password less sudo already setup.

**Comment by LalatenduMohanty** [comment]
@kbsingh as you mentioned we already have passwordless sudo enabled, so IMO security should not be a concern here. It is mostly about  matching other Vagrant boxes out there.

**Comment by LalatenduMohanty** [comment]
Also I think this is something we need to work with https://github.com/purpleidea/oh-my-vagrant .
@purpleidea ?

**Comment by kbsingh** [comment]
this likely needs a wider conversation, perhaps on the centos-devel list ?

**Comment by purpleidea** [comment]
@kbsingh RE: "it might be best to prefer security" -- there's no such thing in the vagrant dev environment.
@LalatenduMohanty We set the root password to work around some of the broken Vagrant boxes out there: https://github.com/purpleidea/oh-my-vagrant/blob/master/vagrant/Vagrantfile#L1154 We could also do the same for the Vagrant user -- it probably hasn't been an issue for the OMV users, because vscreen lets them log in as root directly. Eg; vscreen root@box1

I do recommend building your boxes with the vagrant user password set to `vagrant` though.

HTH

**Comment by kbsingh** [comment]
with a reasonable passage of time, have we hit ( or know someone who has hit ) a problem due to the password not being vagrant ?

**Comment by purpleidea** [comment]
@kbsingh I sometimes use virt-manager to open up a console and login as root/vagrant from time to time. It's also an invaluable way to debug vagrant issues.

**Comment by jjshoe** [comment]
The root password should definitely be set to vagrant. Vagrant machines are use for fast prototyping. Be it code, configuration management, or simply testing something someone else has given you. 

The vagrant private key is distributed with vagrant, and is all over the world. Even if you change vagrant's password, you can assume no security. Setting roots password to vagrant to follow the standard doesn't make it less secure, it simply enables one less step be done manually that folks expect to be done as a standard.

**Comment by LongLiveCHIEF** [comment]
+1 for changing the root password to `vagrant`. Having a bunch of issues downstream when iterating on this as a base using packer.

**Comment by jjulien** [comment]
+1
