### ISSUE TITLE
We should increase the vagrant image disk size to 40GB

### ISSUE THREAD

**Issue by LalatenduMohanty** [CentOS/sig-cloud-instance-build#31]
We should increase the vagrant image disk size to 40GB as the disk space is thin provisioned i.e. it will not take space only when data is written on to it. So increasing disk size does not increase the image size but helps users who need more disk size.

**Comment by kbsingh** [comment]
+1, lets do this, I've already changed the ones in the last builds we pushed.

**Comment by kbsingh** [comment]
https://github.com/CentOS/sig-cloud-instance-build/commit/83ea59927dc1e08b56de8ea19d6eb3d1342de8c4 done
