### ISSUE TITLE
We need the NFS client packages in the CentOS7 Vagrant box

### ISSUE THREAD

**Issue by LalatenduMohanty** [CentOS/sig-cloud-instance-build#32]
We need the NFS client packages (i.e. nfs-utils) in the vagrant box, so that Vagrant box work faster with [vagrant-cachier](https://github.com/fgrehm/vagrant-cachier). Else for each `vagrant up` Vagrant installs nfs client packages from internet to the Vagrant box.

**Comment by kbsingh** [comment]
added https://github.com/CentOS/sig-cloud-instance-build/commit/8beaef3938fa0cdb83520ed44f96a5bf3557451c

nfs-utils brings in an additional 17 rpms as deps, but the overall size impact is an acceptable 4.1mb
