### ISSUE TITLE
Kickstart file for centos-7.2.1511-docker

### ISSUE THREAD

**Issue by iwidanalage** [CentOS/sig-cloud-instance-build#36]
I'm looking for kickstart file for centos-7.2.1511 ( 
https://github.com/CentOS/sig-cloud-instance-images/blob/a3c59bd4e98a7f9c063d993955c8ec19c5b1ceff/docker). Can anyone please point me where I can find this this? Thanks.

**Comment by jperrin** [comment]
for 6 and 7, I've changed up the build practice slightly, and have been working on the appropriate way to document. I'll post these kickstarts soonish, probably in a separate branch at first.

**Comment by iwidanalage** [comment]
Cool, thanks a lot.

**Comment by jperrin** [comment]
This is what's currently used. 

https://github.com/CentOS/sig-cloud-instance-build/tree/livemedia_builds/docker

**Comment by jperrin** [comment]
closing issue to clean things up.
