### ISSUE TITLE
Potentially stale network config in the image

### ISSUE THREAD

**Issue by lpancescu** [CentOS/sig-cloud-instance-build#38]
The network doesn't come up reliably (using Vagrant with VirtualBox on OS X, configured with private_network, which means Vagrant will generate a VM with two NICs). NetworkManager seems to sometimes associate interface `eth0` with device `eth1`, causing dhclient to try to get an address on eth1, where ther's no DHCP server. However, I still see a /etc/resolv.conf:
```
[vagrant@localhost ~]$ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.122.1
```
However, `192.168.122.1` doesn't make any sense: the VirtualBox NAT uses `10.0.2.0/24`, while the second NIC is on the host-only network `192.168.56.0/24`. I suspect `/etc/resolv.conf` might be part of the generated image:
```
[vagrant@localhost ~]$ ls -l /etc/resolv.conf
-rw-r--r--. 1 root 55 Feb 22 12:48 /etc/resolv.conf
[vagrant@localhost ~]$ date
Tue 23 12:36:34 EST 2016
[vagrant@localhost ~]$ uptime
12:36:38 up 14 min,  1 user,  load average: 0.00, 0.16, 0.24
```
I also see an `/etc/sysconfig/network-scripts/ifcfg-eth0` file, also from Feb 22, probably part of the image. It didn't have any `DEVICE` line, just `NAME="eth0"`, so I added `DEVICE="eth0"` and issued `sudo nmcli con reload`. Now `nmcli -t -f NAME,DEVICE con show` displays `eth0:eth0`, and `ip addr show eth0` displays the IP address `10.0.2.15/24`: the network is working properly now.

**Comment by bertvv** [comment]
Why use the old network interface names `eth0`, `eth1`, etc. at all? Why not systemd's predictable interface names (for VirtualBox, e.g. `enp0s3`, `enp0s8`, etc.). Wouldn't that also have solved this issue?

**Comment by lpancescu** [comment]
@bertvv We use Image Factory to generate our images; a single netinst in performed in KVM, and the resulted disk image is converted to different formats for VMware, VirtualBox or Hyper-V, and the rest of the OVF is programatically generated for each type of Vagrant box. The network cards are not guaranteed to be in the same virtual PCI slot for each of these hypervisors. Besides, there has been quite a number of Vagrant bugs wrt the "new" interface names. I think the new interface names are mostly useful for people running Linux on real servers - it's useful to know which of the 8 NICs need to be replaced. For a VM with just a single network card, like Vagrant boxes have, not so much.

**Comment by bertvv** [comment]
@lpancescu Thanks for taking the time to explain! My Vagrant boxes do have multiple interfaces, but I guess I'm a corner case...
