### ISSUE TITLE
Licence file is missing

### ISSUE THREAD

**Issue by mkumatag** [CentOS/sig-cloud-instance-build#57]
Can someone let me know what kind of licence we have for this project? Currently I don't see any LICENCE file in it. It will be grate if we create one. -Thanks.

**Comment by mkumatag** [comment]
@kbsingh @jperrin

**Comment by jperrin** [comment]
@mkumatag please stop tagging us for each and every issue you submit. I see them. I may not respond right away, but that doesn't mean I don't see it.

**Comment by mkumatag** [comment]
Sorry about that..

**Comment by mkumatag** [comment]
Any updates on this?
