### ISSUE TITLE
localedef is missing

### ISSUE THREAD

**Issue by jgeiger** [CentOS/sig-cloud-instance-build#7]
In the latest version of this image not root users get a bunch of issues with locales.

```
-bash: warning: setlocale: LC_CTYPE: cannot change locale (us): No such file or directory
-bash: warning: setlocale: LC_COLLATE: cannot change locale (us): No such file or directory
-bash: warning: setlocale: LC_MESSAGES: cannot change locale (us): No such file or directory
-bash: warning: setlocale: LC_NUMERIC: cannot change locale (us): No such file or directory
-bash: warning: setlocale: LC_TIME: cannot change locale (us): No such file or directory
```

When trying to fix it using localedef, it's not available.
    localedef -c -f UTF-8 -i en_US en_US.UTF-8
fails because the command isn't installed.

You need to remove the package from the DB and then reinstall.
    rpm -e glibc-common
    yum install glibc-common

It would be nice if this were back in by default.

**Comment by jdeathe** [comment]
I don't think locale is necessary in a container and the issue reported here can be resolved by removing the settings from /etc/sysconfig/i18n with either:

```
/usr/bin/truncate -s 0 /etc/sysconfig/i18n
```

OR

```
> /etc/sysconfig/i18n
```

**Comment by coderdad** [comment]
Even after reinstalling glibc-common, I'm still unable to set the charmap:

```
[root@3ac35065b694 ps]# localedef -c -i en_US -f UTF-8 en_US.UTF-8
[root@3ac35065b694 ps]# locale charmap
ANSI_X3.4-1968
[root@3ac35065b694 ps]#
```
